### PR TITLE
Frontend kanban tasks.php (styled with internal CSS for now)

### PR DESCRIPTION
**Pull request by angella-qian**

### CODE REVIEW

**Comment by TANJX** [comment]
Did you create this branch from release 1.0 branch? You should create from develop branch.

**Comment by TANJX** [comment]
What are the files you were working on?

**Comment by james-tyner** [comment]
> Did you create this branch from release 1.0 branch? You should create from develop branch.

I think this happened because when I created a new branch of mine own using the Git tool in Atom, it created it from release (or at least said it did), and so when those changes (PR #9) merged into Angella's branch, her source branch also changed to release

**Comment by james-tyner** [comment]
I'm going to split this branch into a new one, hopefully fix the merge conflicts in the new branch, and then close this PR if that one can successfully merge

**Pull request closed without merging**
